/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Giao_Dien_Bat_Dau;

/**
 *
 * @author Koyomi
 */

import CSDL.CSDL;
import CSDL.DocGia;
import CSDL.TaiKhoan;
import javax.swing.JOptionPane;
public class dang_ki_doc_gia extends javax.swing.JFrame {

    /**
     * Creates new form dang_ki_doc_gia
     */
    public dang_ki_doc_gia() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_tai_khoan = new javax.swing.JTextField();
        txt_mat_khau = new javax.swing.JPasswordField();
        txt_mat_khau_1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_TenNguoiDung = new javax.swing.JTextField();
        txt_NgaySinh = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        txt_NgheNghiep = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Dia_chi = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton1.setText("Đăng kí");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 110, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton2.setText("Đăng Nhập");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 120, -1));
        getContentPane().add(txt_tai_khoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 220, -1));

        txt_mat_khau.setText("jPasswordField1");
        txt_mat_khau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mat_khauActionPerformed(evt);
            }
        });
        getContentPane().add(txt_mat_khau, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 220, -1));

        txt_mat_khau_1.setText("jPasswordField2");
        getContentPane().add(txt_mat_khau_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 220, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tài Khoản");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Mật Khẩu");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 60, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nhập lại mật khẩu");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));
        getContentPane().add(txt_TenNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 220, -1));
        getContentPane().add(txt_NgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 220, -1));
        getContentPane().add(txt_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 220, -1));
        getContentPane().add(txt_NgheNghiep, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 220, -1));

        txt_Dia_chi.setColumns(20);
        txt_Dia_chi.setRows(5);
        jScrollPane1.setViewportView(txt_Dia_chi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 220, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Họ Tên:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 82, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ngày Sinh:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số Điện Thoại:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nghề Nghiệp:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Địa Chỉ:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 62, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setText("ĐĂNG KÍ TÀI KHOẢN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 300, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_image/them_tk_png 50x50.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_image/iconset4/icon/bg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 580, 50));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 130, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean check_pass(){
        char c1[] = txt_mat_khau.getPassword();
        char c2[] = txt_mat_khau_1.getPassword();
        if(c1.length != c2.length) return false;
        for(int i=0; i< c1.length;i++)
            if(c1[i] != c2[i]) return false;
        return true;
    }
    private boolean check_de_trang_thong_tin(){
        if(txt_Dia_chi.getText().equalsIgnoreCase("")) return false;
        if(txt_TenNguoiDung.getText().equalsIgnoreCase("")) return false;
        if(txt_NgaySinh.getText().equalsIgnoreCase("")) return false;
        if(txt_SDT.getText().equalsIgnoreCase("")) return false;
        if(txt_NgheNghiep.getText().equalsIgnoreCase("")) return false;
        if(txt_tai_khoan.getText().equalsIgnoreCase("")) return false;
        if(txt_mat_khau.getPassword().length == 0) return false;
        if(txt_mat_khau_1.getPassword().length == 0) return false;
        return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!check_de_trang_thong_tin()) JOptionPane.showMessageDialog(this, "Không được để trắng thông tin");
        else if(!check_pass()) JOptionPane.showMessageDialog(this, "Mật khẩu không khớp");
        else if(!CSDL.check_TaiKhoan_ton_tai(txt_tai_khoan.getText())) JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại");
        else {
            // them thong tin nguoi dung
            DocGia x = new DocGia();
            x.setTenNguoiDung(txt_TenNguoiDung.getText());
            x.setNgaySinh(txt_NgaySinh.getText());
            x.setNgheNghiep(txt_NgheNghiep.getText());
            x.setSDT(txt_SDT.getText());
            x.setDiaChi(txt_Dia_chi.getText());
            CSDL.add_DocGia(x);
            // them thong tin tai khoan
            TaiKhoan y = new TaiKhoan();
            y.settaikhoan(txt_tai_khoan.getText()); // lay ten tk
            char tmp[] = txt_mat_khau.getPassword(); // lay matkhau
            String pass = "";
            for(char i : tmp) pass+=i;
            y.setMatkhau(pass);
            // lay ID_DOC_GIA
            y.setID_DocGia(CSDL.tim_kiem_ID_DocGia(x));
            CSDL.add_TaiKhoan(y);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_mat_khauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mat_khauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mat_khauActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dang_nhap_doc_gia dk = new dang_nhap_doc_gia();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dang_ki_doc_gia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dang_ki_doc_gia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dang_ki_doc_gia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dang_ki_doc_gia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dang_ki_doc_gia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_Dia_chi;
    private javax.swing.JTextField txt_NgaySinh;
    private javax.swing.JTextField txt_NgheNghiep;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenNguoiDung;
    private javax.swing.JPasswordField txt_mat_khau;
    private javax.swing.JPasswordField txt_mat_khau_1;
    private javax.swing.JTextField txt_tai_khoan;
    // End of variables declaration//GEN-END:variables
}
